### ISSUE TITLE
Module not found: Can't resolve 'react/lib/React'

### ISSUE THREAD

**Issue by snrn-Pontus** [everydayhero/prismic-utils#27]
Hello! I was unable to use this until I removed "var _server = require('react-dom/server');" from prismic-utils/dist/deserialize/index.js

Do you have any idea if this is something you could solve? I am using react 16.0.0 and react-dom 16.0.0

**Comment by ellsclytn** [comment]
We don't currently support React ^16, until Prismic bump support for their `prismic-reactjs` module. Downgrading to ^15 should resolve for now.
